### ISSUE TITLE
investigate how to create a service to sync the World ID merkle tree (currently only done by signup-sequencer)

### ISSUE THREAD

**Issue by dragan2234** [dragan2234/worldcoin-scroll-bridge#1]
signup-sequencer: https://github.com/worldcoin/signup-sequencer

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-scroll-bridge).

### My background and how it can be leveraged

I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged
Hello Project Lead! I'm Ugo, a fullstack Blockchain Dev(js,React,Node,Next.js,Three.js, solidity, Cairo) developer with a strong track record in OD hack projects. I've been actively involved since Edition 1, contributing to various initiatives, and I'm thrilled to be part of Edition 6!
Having used OnlyDust extensively (see my profile: https://app.onlydust.com/u/Ugo-X)), I'm confident in my ability to tackle new challenges within this edition.
I'm eager to leverage my skills and experience to contribute effectively.



### How I plan on tackling this issue
Based on the available description, this is something that i can handle although it'd be apt to have more description added to the task for the purpose of clarity.

**Comment by Jayse007** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-scroll-bridge).

### My background and how it can be leveraged
I am a backend developer. I work with Pyghon and have intensive knowledge about data structures.

### How I plan on tackling this issue
I would make accurate and precise research about the stated topic and present well organised documentation dependent on your specifications. It would be delivered within 48 hours

**Comment by Ugo-X** [comment]
Thanks, chief, I will get to it, and keep you updated on my progress.
