### ISSUE TITLE
investigate how to create a relayer service that periodically calls propagateRoot() as a cron job

### ISSUE THREAD

**Issue by dragan2234** [dragan2234/worldcoin-scroll-bridge#3]

**Comment by SwineCoder101** [comment]
picking up this task from the deployments in issue #4

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-scroll-bridge).

### My background and how it can be leveraged

I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged
Hello Project Lead! I'm Ugo, a fullstack Blockchain Dev(js,React,Node,Next.js,Three.js, solidity, Cairo) developer with a strong track record in OD hack projects. I've been actively involved since Edition 1, contributing to various initiatives, and I'm thrilled to be part of Edition 6!
Having used OnlyDust extensively (see my profile: https://app.onlydust.com/u/Ugo-X)), I'm confident in my ability to tackle new challenges within this edition.
I'm eager to leverage my skills and experience to contribute effectively.

**Comment by zkCaleb-dev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/worldcoin-scroll-bridge).

### My background and how it can be leveraged
I have experience with Linux ecosystems and jobs scheduled with cron using crontab. I have also worked on various projects that use TypeScript, .NET, and Java, so I have experience solving logical problems.

### How I plan on tackling this issue
Understanding the Requirements: I would start by comprehensively understanding what propagateRoot() does and its role within the system.

Setting Up the Environment: I would ensure that the necessary environment (like network, permissions, and dependencies) is correctly configured for the relayer service.

Writing the Script: I would write a script that invokes the propagateRoot() function. This script should include error handling and logging mechanisms to monitor the process.

Scheduling with Cron: Finally, I would set up a cron job to execute this script at the required intervals. I would test the cron job to ensure it runs correctly and make any necessary adjustments.

**Comment by dragan2234** [comment]
hi @zkCaleb-dev i have assigned you the issue

**Comment by dragan2234** [comment]
hi @zkCaleb-dev is there any update on this?

**Comment by Jemiiah** [comment]
Hello @dragan2234 please I would love to contribute to this project and work on this issue ser 🙌🏾
